Define model:

In [1]:
import torch

class TinyModel(torch.nn.Module):

    def __init__(self):
        super(TinyModel, self).__init__()

        self.bn = torch.nn.BatchNorm2d(1)

    def forward(self, x):
        x = self.bn(x)
        return x

model = TinyModel()

Define sample tensor:

In [2]:
C = 2

x = torch.Tensor([[[1,2],
                   [3,4]]])
x = x.unsqueeze(0)
print(x.shape)

torch.Size([1, 1, 2, 2])


Bessel's correction is correection = 1, we can manually set correction = 0.

correction = 0:

 $\sigma = \sqrt{\frac{1}{N}\sum\limits_{i=0}^{N-1}(x_i - \bar x)^2}$

correction = 1:

  $\sigma = \sqrt{\frac{1}{N-1}\sum\limits_{i=0}^{N-1}(x_i - \bar x)^2}$

In [3]:
model.train()
y = model(x)

x_ = x[0,0,:,:]
y_ = y[0,0,:,:]

print('\noutput tensor:')
print(y)

print('\ncorrection = 1')
print((x-torch.mean(x))/torch.std(x))

print('\ncorrection = 0')
print((x-torch.mean(x))/torch.std(x, correction = 0))


output tensor:
tensor([[[[-1.3416, -0.4472],
          [ 0.4472,  1.3416]]]], grad_fn=<NativeBatchNormBackward0>)

correction = 1
tensor([[[[-1.1619, -0.3873],
          [ 0.3873,  1.1619]]]])

correction = 0
tensor([[[[-1.3416, -0.4472],
          [ 0.4472,  1.3416]]]])


This implies that BN returns samples with mean $\mu = 0$ but std $\sigma \neq 1$ (specifically $\sigma > 1$). If the sample size is big, $N >> 0$, then $\sqrt{\frac{1}{N}} \approx \sqrt{\frac{1}{N-1}}$, hence $\sigma \approx 1$.